### ISSUE TITLE
GherkinSpec.Model does not exist in the namespace 'GherkinSpec' 

### ISSUE THREAD

**Issue by AndyRB** [GivePenny/GherkinSpec#26]
Currently receive the following error when trying to reference GherkinSpec.Model.DataTable:
`The type or namespace name 'Model' does not exist in the namespace 'GherkinSpec' (are you missing an assembly reference?)`

Currently GherkinSpec.Model.dll is packaged to the build folder, does this need to be lib folder?
```
<_PackageFiles Include="$(OutputPath)\GherkinSpec.Model.dll">
      <BuildAction>None</BuildAction>
      <PackagePath>build/netstandard2.0</PackagePath>
    </_PackageFiles>
```

**Comment by DaveAurionix** [comment]
@AndyRB thanks for that.  A new package (1.0.8) has been published and should now be listed on Nuget - could you give that a try and let us know if this is solved from your perspective?

**Comment by AndyRB** [comment]
All good for me,. thanks
