### ISSUE TITLE
Visual Studio Text Explorer - Duplicate scenario names are not handled

### ISSUE THREAD

**Issue by carl-hartshorn** [GivePenny/GherkinSpec#45]
When a scenario name is duplicated (either within or across feature files) the Visual Studio Test Explorer only picks up the first scenario it encounters.

Encountered in Visual Studio (2019 Community - Version 16.2.5).

The problem isn't manifested when running `dotnet test` - all scenarios with the same name run in this case.

Although scenarios with the same name may be confusing and not something we want to support, the present behaviour is also potentially confusing. This is particularly so when a scenario with a duplicated name fails. Running the tests using the VS Test Explorer appears to show that all tests are passing. Running via `dotnet test` or `dotnet vstest` (potentially on a build agent) shows the test failure.

The issue has been reproduced in this branch: https://github.com/GivePenny/GherkinSpec.SimpleExample/tree/duplicate-scenario-names

I'm happy to work on a PR to resolve this. @DaveAurionix what are your thoughts on a solution? We could fail when detecting duplicate scenario names, although the experience when this happens (for example when a feature file is not syntactically correct) isn't great. An alternative might be to append the duplicated scenario names with a counter of some sort.

**Comment by DaveAurionix** [comment]
@carl-hartshorn Thanks for raising this.  The counter at the end of the scenario name seems like the best solution?

You're probably already thinking along this line, but I wondered about putting the counter in brackets to try to keep it as natural-language as possible - i.e. "Scenario Name (2)" is more friendly than "Scenario Name2".
