### ISSUE TITLE
Add support for non-english feature files

### ISSUE THREAD

**Issue by metareven** [GivePenny/GherkinSpec#47]
I tried using GherkinSpec in a project with Norwegian feature files, but I am unable to run the tests as I only get an exception saying:

`Skipping assembly because an exception was thrown: GherkinSpec.Model.Parsing.InvalidGherkinSyntaxException: Expected the first line of a feature file to start with 'Feature:' or a tag.
`

This is an essential feature for my team as our acceptance criterias are all written in Norwegian and we do not wish things to possibly get "lost in translation" when being converted to tests.
You can find a set of translations from english to other languages here: https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin-languages.json

**Comment by DaveAurionix** [comment]
@metareven Thank you for raising this.  I completely agree with your point regarding not "losing things in translation".  Localisation is something that we want to support.  We'll start working on a pull-request for localisation with Norwegian as the first language we implement.

GherkinSpec is a tool that we wrote because we needed it.  We recognise that it isn't something that will suit everyone's needs and we don't intend to make money from it.  That means that it might take us a while to complete the feature, but once we're ready I'll respond here.  Would you be happy to keep hold of your trial project and test the first version that supports the Norwegian language when it's ready?

**Comment by metareven** [comment]
I will be more than happy to test this out once it becomes available :)

**Comment by DaveAurionix** [comment]
@metareven Thank you.  Just in case you notice code being merged, this is work in progress. We have failing tests at the moment that we need to look into.  I'll respond again when we have something that is fit to share.

**Comment by DaveAurionix** [comment]
@metareven We have a version ready for you to look at.  If you update to the latest package (version 2.0.7 onwards) and let us know how you get on that would be great.

Documentation is here, do let us know if something isn't clear: https://github.com/GivePenny/GherkinSpec/blob/master/docs/Localisation.md

... and apologies in advance for our poor Norwegian!

**Comment by DaveAurionix** [comment]
We've implemented support for BokmÃ¥l as the first language (if I have used that term correctly).  If that was an unusual choice for Norwegian tests generally, please let us know what would be a better choice and send us suitable translations for the phrases found in this file lines 120 onwards (link below).  We'd be happy to add them in for you.  If we tried to translate these ourselves we'd be using Google Translate or Bing Translations and we wouldn't know if the results were sensible (sorry!).

https://github.com/GivePenny/GherkinSpec/blob/master/GherkinSpec.Model/Resources/LocalisedContent.nb-NO.resx#L120-L155

**Comment by metareven** [comment]
I've ran some tests and it seems to work for the feature Given and When steps (Gitt, Når), but not for the Then step (Så). If I rewrite my steps and feature files, replacing all instances of Then/Så with When/Når then everything works fine. This indicates that something is wrong when trying to find step definitions for the Så keyword. 
This is the stacktrace I get:
```
Error Message:
   Could not find a step definition to match the step 'Så skal strengen som ble gitt som input printes'.
  Stack Trace:
     at GherkinSpec.TestAdapter.Binding.StepBinder.GetBindingFor(IStep step, Dictionary`2 regularExpressionsToMethods)
   at GherkinSpec.TestAdapter.Binding.StepBinder.GetBindingForStepWithoutCache(IStep step, Assembly testAssembly)
   at GherkinSpec.TestAdapter.Binding.StepBinder.<>c__DisplayClass5_0.<GetBindingFor>b__0(IStep keyStep)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at GherkinSpec.TestAdapter.Binding.StepBinder.GetBindingFor(IStep step, Assembly testAssembly)
   at GherkinSpec.TestAdapter.Execution.StepsExecutor.ExecuteSteps(IServiceProvider serviceProvider, TestResult testResult, IEnumerable`1 steps, DiscoveredTestData testData, TestRunContext testRunContext)
   at GherkinSpec.TestAdapter.Execution.StepsExecutor.Execute(TestCase testCase, DiscoveredTestData testData, TestRunContext testRunContext, IMessageLogger logger)
```

Bokmål is a good starting language to support for Norwegian as it is used by approx 88% of the population. I also took a look at https://github.com/GivePenny/GherkinSpec/blob/master/GherkinSpec.Model/Resources/LocalisedContent.nb.resx and the translations there seem to be correct and according to the link I sent you.

**Comment by DaveAurionix** [comment]
Thanks for your work.  We're looking into the problem you found.

**Comment by DaveAurionix** [comment]
@metareven The problem with the Så step should now be fixed in the 2.0.10 package that has just been published.

**Comment by metareven** [comment]
Tried with a few different feature files now and everything seems to be in order.
I'll close this issue and rather make new issues down the line if I find anything iffy about the L11N

Good job :)

**Comment by DaveAurionix** [comment]
@metareven Thanks for your help, and yes please do let us know if you hit any problems.
